services:
  airflow:
    build: .
    container_name: airflow_hiring
    restart: always

    ports:
      - "8080:8080"         # UI Airflow

    environment:
      # no cargar DAGs de ejemplo y usar SQLite+SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor

    volumes:
      - ./dags:/opt/airflow/dags:ro
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs

    # el entrypoint maneja db init, scheduler y webserver
    command: []
